### PR TITLE
Add colorpicker and codecompletion to editor

### PR DESCRIPTION
**Pull request by EthanLowenthal**
## Adds two extensions to the shadertoy code editor.
This is something I did for myself, but I figured it can be put into the extension if others are interested. Before this is mergerd, some code should be cleaned up to be more consistent with the project style.
gif
### Color picker:
If you put your cursor over any vec3 with 3 floats in it, a color picker will pop up and you can edit the color of the vec3.
Screen Shot 2020-11-28 at 7 31 59 PM
Screen Shot 2020-11-28 at 8 15 15 PM

It uses the `<input type="color">` which layout and style changes based on browser. 
The vec3 will match `vec3(1.,.2,2.1)` or any combination of the glsl floats

### Code completion:
This is a plugin someone else wrote for codemirror that I slightly modified. It adds code completion when you press shift-tab (you can change the keybind on line 800 of shadertoy-plugin-codemirror.js). I also added two code snippets but this extension is more built for code completion and in the future maybe I can modify it to be better with code snippets.
Screen Shot 2020-11-28 at 7 33 07 PM
The code completion only uses a predefined list of terms (see line 620 of shadertoy-plugin-codemirror.js) and does not 'smart' complete custom variables or functions

### Changed files:
added shadertoy-plugin-codemirror.js --  the codemirror plugins
modified contentscript.js -- added loader for codemirror plugin on shadertoy/view/* and shadertoy/new urls
modified manifest.json -- allows loading of shadertoy-plugin-codemirror.js

### CODE REVIEW

**Comment by EthanLowenthal** [comment]
I just realized my linter auto-changed a few things contentscript.js. I can revert if you would like.

**Comment by patuwwy** [comment]
Thanks for Your work! 
I am sure that many people will be pleased with these additions.


> Before this is mergerd, some code should be cleaned up to be more consistent with the project style.

Your code is completely independent of my extension. Would you consider putting it in the 'app/ext' or 'app/add-ons' directory. Then I would have no problems with the code style or formatting :)


> I just realized my linter auto-changed a few things contentscript.js. I can revert if you would like.

Please use provided linters configuration files for contentscipt.js.


> It adds code completion when you press shift-tab (you can change the keybind on line 800 of shadertoy-plugin-codemirror.js). 

Could You add key binding info to popup?

**Comment by EthanLowenthal** [comment]
I implemented your requests. Please let me know if there is anything else. I considered adding an option to disable the codemirror add-ons but I'm not sure if that is something that is super important because they are not too invasive to people using the editor. I also don't want to be too invasive on what you have already set up.

**Comment by patuwwy** [comment]
One more thing :)

Please update following files:

- manifest.json
 Change version to 0.13.215

- CHANGELOG.md
add info about introduced features. in one sentence.

- README.md
add info about features, screenshots are welcome!

When done, PR will be merged and new version will be published

**Comment by EthanLowenthal** [comment]
Done.

**Pull request merged**
