### PR TITLE
feature: profile page shaders list preview images

### PR DESCRIPTION
**Pull request by movAX13h**
Hi!

I found this feature very useful so I implemented it. Maybe you like it too and want to add a checkbox to the config panel. Another possibility would be to show the images on mouse over in a floating div next to the mouse cursor instead of loading all (and wasting quite a lote space). Adjustable image size would be nice too.

Screenshot

best regards,
movAX13h

### CODE REVIEW

**Comment by patuwwy** [comment]
It is cool feature! Love it!

I will look at it closer in couple of days but for sure it will be merged and released.

Maybe to merge ideas about decrease preview size on the list and and popup with hover with full size? What do You think?

**Comment by movAX13h** [comment]
Sounds good to me. The original image size is 640x360 (have not tested if it depends on browser size when saving a shader) so maybe a custom-sized image preview and a bigger overlay on mouse-hover. There's a lot of space available to the left of the list so maybe put the overlay image there.

I can do all of this if you have no time to do it in the next couple of days. Just let me know.

**Comment by patuwwy** [comment]
Yes, please. Feel free to do it. I am busy till monday. Then I can merge your code and release new version in chrome store. Please don't forget to add yourself to credits ;-)

**Comment by movAX13h** [comment]
Soo... I've added the preview image overlay. It shows when hovering the "icon" next to the shader name. I think it's a good solution that does not require any settings in the config panel.

I have updated the version number in manifest.json to 0.4.2 and added a new entry in the changelog in README.md. I found a small typo in popup.html (fond != font) and fixed it.

Everything should be ready for release.

**Comment by patuwwy** [comment]
Great. Will be released today / tomorrow.

**Pull request merged**
